### ISSUE TITLE
ODC not locking serial port

### ISSUE THREAD

**Issue by agilbett** [neilstephens/opendatacon#19] opened 2016-10-26 06:14 UTC
In addition to #18 ODC is not locking the serial port. The same config applies.

**Comment by neilstephens** [comment] 2016-10-27 00:11
I agree this is an issue, but the problem is in the opendnp3 library (that's where the code is that opens the serial device). I'll check if it's been fixed in the latest opendnp3, and if not, I'll open an issue/pull request to see if we can get it fixed.

Cheers,
Neil.

**Closed by neilstephens** 2016-10-27 00:11 UTC

**Comment by neilstephens** [comment] 2016-10-27 00:38
After a bit more digging, the serial port open is actually handled in the asio library, so it's not even an opendnp3 issue...
